/*
 * ProtocolInterface.c
 *
 *  Created on: Jul 7, 2025
 *      Author: xiaoqin.hou
 */

#include "ProtocolInterface.h"
#include "ProtocolCommand.h"

ProtocolDefinition* gProtocol=NULL;


void print_buffer_hex(const uint8_t* buffer, size_t size) {
    for (size_t i = 0; i < size; i++) {
        printf("%02X ", buffer[i]); // %02X 表示两位大写十六进制
        if ((i + 1) % 16 == 0) {   // 每16个字节换行
            printf("\n");
        }
    }
    printf("\n");
}

void print_command(const Command* cmd) {
    if (!cmd) {
        printf("Command is NULL.\n");
        return;
    }

    printf("Command ID: %u\n", cmd->id);
    printf("Command Name: %s\n", cmd->name ? cmd->name : "(null)");
    printf("Field Count: %u\n", cmd->field_count);

    for (uint16_t i = 0; i < cmd->field_count; ++i) {
        const CommandField* field = &cmd->fields[i];
        printf("  Field #%u (type %d): ", field->field_num, field->type);

        switch (field->type) {
            case TYPE_UINT8:
                printf("uint8 = %u\n", field->value.uint8_val);
                break;
            case TYPE_UINT16:
                printf("uint16 = %u\n", field->value.uint16_val);
                break;
            case TYPE_UINT32:
                printf("uint32 = %u\n", field->value.uint32_val);
                break;
            case TYPE_UINT64:
                printf("uint64 = %u\n", field->value.uint64_val);
                break;
            case TYPE_INT8:
                printf("int8 = %d\n", field->value.int8_val);
                break;
            case TYPE_INT16:
                printf("int16 = %d\n", field->value.int16_val);
                break;
            case TYPE_INT32:
                printf("int32 = %d\n", field->value.int32_val);
                break;
            case TYPE_INT64:
                printf("int64 = %%d\n", field->value.int64_val);
                break;
            case TYPE_BOOL:
                printf("bool = %s\n", field->value.bool_val ? "true" : "false");
                break;
            case TYPE_FLOAT:
                printf("float = %f\n", field->value.float_val);
                break;
            case TYPE_DOUBLE:
                printf("double = %lf\n", field->value.double_val);
                break;
            case TYPE_STRING:
                printf("string = \"%s\"\n", field->value.string_val ? field->value.string_val : "(null)");
                break;
            case TYPE_BYTES:
                printf("bytes = ");
                for (uint32_t j = 0; j < field->value.bytes_val.length; ++j) {
                    printf("%c", field->value.bytes_val.data[j]);
                }
                printf(" (len=%u)\n", field->value.bytes_val.length);
                break;

            default:
                printf("(unknown type)\n");
                break;
        }
    }
}

void ProtocolInterface_Init(void)
{
    // 1. 配置帧头帧尾
    uint8_t my_header[] = {0xEE, 0xFF}; // 示例帧头
    uint8_t my_footer[] = {0xFF, 0xFC, 0xFF, 0xFF}; // 示例帧尾
    uint8_t CMD_ID_TAG = 0x08;      // (1 << 3) | 0 (varint)
    uint8_t CMD_NAME_TAG = 0x12;     // (2 << 3) | 2 (length-delimited)
    uint8_t PAYLOAD_TAG = 0x1A;      // (3 << 3) | 2 (length-delimited)
    uint8_t SUCCESS_TAG = 0x10;      // (2 << 3) | 0 (varint)
    uint8_t RESPONSE_DATA_TAG = 0x1A;// (3 << 3) | 2 (length-delimited)

    FrameConfig frame_cfg = {
        .header = my_header,
        .header_size = sizeof(my_header),
        .footer = my_footer,
        .footer_size = sizeof(my_footer),
        .CMD_ID_TAG = CMD_ID_TAG,
        .CMD_NAME_TAG = CMD_NAME_TAG,
        .PAYLOAD_TAG = PAYLOAD_TAG,
        .SUCCESS_TAG = SUCCESS_TAG,
        .RESPONSE_DATA_TAG = RESPONSE_DATA_TAG
    };
    
    // 2. 初始化协议
    protocol_init(&frame_cfg);

    // Load protocol definition (could be from file or string)
    // ProtocolDefinition* protocol = protocol_load_from_file("/mnt/extra/projects/Git/HGPro/processes/CommonCommunicationDemoC/protocol_commands.json");
    const char* protocol_json = 
    "{\n"
    " \"protocol_version\": \"1.0\", \n"
    " \"commands\": [\n"
    "  {\n"
    "    \"id\": 1,\n"
    "    \"name\": \"GetVersion\", \n"
    "    \"metadata\": {\n"
    "      \"require_ack\": false\n"
    "    },\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"major\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": 0\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"minor\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"patch\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 3,\n"
    "        \"default\": 0\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 2,\n"
    "    \"name\": \"SetParameter\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"end_potential\",\n"
    "        \"type\": \"uint16\",\n"
    "        \"field_num\": 1,\n"
    "        \"description\": \"终点电位\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"end_drift\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"description\": \"终点漂移\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"start_drift\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 3,\n"
    "        \"description\": \"起始漂移\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"end_delay\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 4,\n"
    "        \"description\": \"终点延时\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"calibration_factor\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 5,\n"
    "        \"description\": \"校正因子\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"min_duration\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 6,\n"
    "        \"description\": \"最短时长\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"max_duration\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 7,\n"
    "        \"description\": \"最长时长\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"extraction_time\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 8,\n"
    "        \"description\": \"萃取时间\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"termination_time\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 9,\n"
    "        \"description\": \"终止时间\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"electrolytic_electrode\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 10,\n"
    "        \"description\": \"电解电极\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"fan\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 11,\n"
    "        \"description\": \"风扇\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"heater_tube\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 12,\n"
    "        \"description\": \"加热伴管\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"initial_temperature\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 13,\n"
    "        \"description\": \"初始温度\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"constant_temperature_time\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 14,\n"
    "        \"description\": \"恒温时间\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"program_heating\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 15,\n"
    "        \"description\": \"程序升温\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"rate1\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 16,\n"
    "        \"description\": \"速率1\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"rate2\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 17,\n"
    "        \"description\": \"速率2\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"rate3\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 18,\n"
    "        \"description\": \"速率3\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"temperature1\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 19,\n"
    "        \"description\": \"温度1\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"temperature2\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 20,\n"
    "        \"description\": \"温度2\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"temperature3\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 21,\n"
    "        \"description\": \"温度3\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"keep_warm1\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 22,\n"
    "        \"description\": \"保温1\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"keep_warm2\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 23,\n"
    "        \"description\": \"保温2\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"keep_warm3\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 24,\n"
    "        \"description\": \"保温3\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 3,\n"
    "    \"name\": \"GetData\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": false\n"
    "    },\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"fan_status\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "        \"description\": \"风扇状态,0-关,1-开\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"heating_temperature\",\n"
    "        \"type\": \"float\",\n"
    "        \"field_num\": 2,\n"
    "        \"description\": \"加热温度\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"current_temperature\",\n"
    "        \"type\": \"float\",\n"
    "        \"field_num\": 3,\n"
    "        \"description\": \"当前温度\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"airflow_speed\",\n"
    "        \"type\": \"float\",\n"
    "        \"field_num\": 4,\n"
    "        \"description\": \"气流速度\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"voltage\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 5,\n"
    "        \"description\": \"电压\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"electrolysis_speed\",\n"
    "        \"type\": \"float\",\n"
    "        \"field_num\": 6,\n"
    "        \"description\": \"电解速度\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"analysis_duration\",\n"
    "        \"type\": \"string\",\n"
    "        \"field_num\": 7,\n"
    "        \"description\": \"分析时长\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"water_quality\",\n"
    "        \"type\": \"float\",\n"
    "        \"field_num\": 8,\n"
    "        \"description\": \"水质量\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"status_result\",\n"
    "        \"type\": \"string\",\n"
    "        \"field_num\": 9,\n"
    "        \"description\": \"状态结果\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"flag\",\n"
    "        \"type\": \"string\",\n"
    "        \"field_num\": 10,\n"
    "        \"description\": \"标志\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"drift\",\n"
    "        \"type\": \"float\",\n"
    "        \"field_num\": 11,\n"
    "        \"description\": \"漂移\"\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"blank\",\n"
    "        \"type\": \"float\",\n"
    "        \"field_num\": 12,\n"
    "        \"description\": \"空白\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 4,\n"
    "    \"name\": \"Heating\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"status\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "        \"description\": \"加热使能,0-停止加热,1-开始加热\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 5,\n"
    "    \"name\": \"Fanning\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"status\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "        \"description\": \"风扇使能,0-关,1-开\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 6,\n"
    "    \"name\": \"Pumping\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"status\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "        \"description\": \"气泵使能,0-关,1-开\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 7,\n"
    "    \"name\": \"SetSwirlSpeed\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"speed\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "        \"description\": \"设置搅拌速度1-15档\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 8,\n"
    "    \"name\": \"GetSwirlSpeed\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": false\n"
    "    },\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"speed\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": 0,\n"
    "		 \"description\": \"读取搅拌速度1-15档\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 9,\n"
    "    \"name\": \"ExecuteToCleaningPos\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "       \"name\": \"number\",\n"
    "       \"type\": \"uint8\",\n"
    "       \"field_num\": 1,\n"
    "		\"description\": \"转盘执行到吹扫位,0--非使能,1--使能\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 10,\n"
    "    \"name\": \"GetDiskNumber\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": false\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"number\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": 0,\n"
    "		 \"description\": \"获取盘位号\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 11,\n"
    "    \"name\": \"ExecuteCirculate\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"number\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"设置盘位号0-36,并转盘执行\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 12,\n"
    "    \"name\": \"SampleDetect\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"number\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"检测做样,0--非使能,1--使能\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 13,\n"
    "    \"name\": \"NeedleRaised\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"number\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"穿刺针抬起,0--非使能,1--使能\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 14,\n"
    "    \"name\": \"NeedleToLimitPosition\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"number\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"穿刺针到限位,0--非使能,1--使能\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 15,\n"
    "    \"name\": \"GetNeedlePos\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": false\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"number\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"default\": 0,\n"
    "		 \"description\": \"获取穿刺针当前位置\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 16,\n"
    "    \"name\": \"NeedleLongPress\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"number\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"穿刺针长按,0--非使能,1--使能\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 17,\n"
    "    \"name\": \"NeedleMoveStep\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"step\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"穿刺针步进步数\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 18,\n"
    "    \"name\": \"NeedleToHigh\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"step\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"穿刺针到高位置\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 19,\n"
    "    \"name\": \"NeedleToMedium\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"step\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"穿刺针到中位置\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 20,\n"
    "    \"name\": \"NeedleToLow\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"step\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"穿刺针到低位置\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 21,\n"
    "    \"name\": \"StopGetNeedlePos\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"step\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"停止获取穿刺针位置\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 22,\n"
    "    \"name\": \"SaveCurNeedlePos\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"value\",\n"
    "        \"type\": \"float\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"保存穿刺针位置值\"\n"
    "      },\n"
    "	   {\n"
    "	     \"name\": \"level\",\n"
    "	     \"type\": \"uint8\",\n"
    "	     \"field_num\": 2,\n"
    "	     \"description\": \"保存的穿刺针位置高度等级,0--高,1--中,2--低\"\n"
    "	   }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  },\n"
    "  {\n"
    "    \"id\": 23,\n"
    "    \"name\": \"StartBalance\",\n"
    "    \"metadata\": {\n"
    "      \"require_ack\": true,\n"
    "      \"timeout_ms\": 1000\n"
    "    },\n"
    "    \"request_fields\": [\n"
    "      {\n"
    "        \"name\": \"value\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 1,\n"
    "		 \"description\": \"平衡使能,0--非使能,1--使能\"\n"
    "      }\n"
    "    ],\n"
    "    \"response_fields\": [\n"
    "      {\n"
    "        \"name\": \"success\",\n"
    "        \"type\": \"bool\",\n"
    "        \"field_num\": 1,\n"
    "        \"default\": false\n"
    "      },\n"
    "      {\n"
    "        \"name\": \"error_code\",\n"
    "        \"type\": \"uint8\",\n"
    "        \"field_num\": 2,\n"
    "        \"default\": 0,\n"
    "        \"description\": \"0=success, 1=invalid_id, 2=out_of_range\"\n"
    "      }\n"
    "    ]\n"
    "  }\n"
    "]\n"
"}\n";
    gProtocol = protocol_load_from_string(protocol_json);
    if (!gProtocol) {
        // Handle error
        return;
    }
}
void getSendCommand(uint32_t cmd_id, 
                    CommandMode mode, 
                    const FieldInput *fields, 
                    uint32_t field_count,
                    uint8_t *tx_buffer, 
                    uint32_t *tx_size) 
{ 
    Command* cmd = protocol_create_command(gProtocol, cmd_id);
    if (!cmd) {
        printf("Error: command %u create failed\n", cmd_id);
        return;
    }

    if (mode == CMD_WRITE && fields && field_count > 0) {
        for (uint32_t i = 0; i < field_count; i++) {
            protocol_set_field(cmd, 
                               fields[i].field_num, 
                               fields[i].type, 
                               fields[i].value);
        }
    }

    protocol_encode_command(cmd, tx_buffer, sizeof(uint8_t) * (*tx_size), tx_size);
    print_buffer_hex(tx_buffer, *tx_size);

    protocol_free_command(cmd);
}

Command* getReceiveCommand(uint8_t *rx_buffer, uint32_t *rx_size, uint8_t *tx_buffer, 
                    uint32_t *tx_size){
    Command* rec_cmd=NULL;
    protocol_decode_command(rx_buffer, rx_size, gProtocol, &rec_cmd);
    if (!rec_cmd) {
        printf("Error: decode failed\n");
        return NULL;
    }
    print_command(rec_cmd);
    if (rec_cmd->is_response) return rec_cmd;

    // response
    uint32_t cmd_id = rec_cmd->id;

    const CommandDefinition* cmd_def = find_command_by_id(gProtocol, cmd_id);
    bool has_resp = false;
    // 1. 检查 cmd_id 是否存在于协议
    if (!cmd_def){
        printf("Error: command not found\n");
        // 不存在，构造错误响应
        // protocol_set_field(rec_cmd, 1, TYPE_BOOL, (FieldValue){.bool_val = false});
        // protocol_set_field(rec_cmd, 2, TYPE_UINT8, (FieldValue){.uint8_val = 1}); // invalid_id
    }  else {
        has_resp = (cmd_def->metadata.require_ack);
        if (has_resp){
            // 正常成功
            Command* cmd = create_response_command(cmd_def);
            protocol_set_field(cmd, 1, TYPE_BOOL, (FieldValue){.bool_val = true});
            protocol_set_field(cmd, 2, TYPE_UINT8, (FieldValue){.uint8_val = 0}); // success
            // 编码响应
            protocol_encode_response(cmd, tx_buffer, sizeof(uint8_t) * (*tx_size), tx_size);
            printf("cmd_id: %d, response:\n", cmd_id);
            print_buffer_hex(tx_buffer, *tx_size);
        }
    }
    
    
    return rec_cmd;
}
void ProtocolInterface_deInit(void){
    protocol_free_definition(gProtocol);
    protocol_cleanup();
}