set(LIBRARY_VERSION_MAJOR 1)
set(LIBRARY_VERSION_MINOR 0)
set(LIBRARY_VERSION_PATCH 0)

HG_CMAKE_ADD_MODULE(HwLowerPC inc src)


if (PLATFORM STREQUAL "x64")
HG_CMAKE_MODULE_DEPEND_PUB( 
    HGBaseCommon
    ${LIB_SERIALPORT_LIBRARY}
    ${Boost_LIBRARIES}
    ${CUPS_LIBRARY}
)

HG_CMAKE_ADD_SHARED(HGHwLowerPC inc src)

HG_CMAKE_MODULE_DEPEND(
    HGBaseCommon
    ${LIB_SERIALPORT_LIBRARY}
    ${Boost_LIBRARIES}
    ${CUPS_LIBRARY}
)
elseif (PLATFORM STREQUAL "win32")

HG_CMAKE_ADD_STATIC(HGHwLowerPC inc src)

target_link_libraries(HGBaseCommon  
    ${LIB_SERIALPORT_LIBRARY}
    ${HG_PROJECT_ROOT_FS}/lib/libssl.a
    ${HG_PROJECT_ROOT_FS}/lib/libcrypto.a
    ${HG_PROJECT_ROOT_FS}/lib/libssh.a
    ${HG_PROJECT_ROOT_FS}/lib/libzlibstatic.a
    ws2_32 iphlpapi)
endif()

set_target_properties(HGHwLowerPC PROPERTIES 
    VERSION ${LIBRARY_VERSION_MAJOR}.${LIBRARY_VERSION_MINOR}.${LIBRARY_VERSION_PATCH}
    SOVERSION ${LIBRARY_VERSION_MAJOR}
)