#ifndef IFERROR_H
#define IFERROR_H

#include "IfError_global.h"
#include <string>

namespace HGMACHINE {

enum class HGErrorSeverity {
    INFO,
    WARNING,
    ERROR,
    CRITICAL
};

enum class HGErrorCode {
    SUCCESS = 0,
    
    SYSTEM_ERROR_BASE = 1000,
    SYSTEM_INIT_FAILED = 1001,
    SYSTEM_RESOURCE_UNAVAILABLE = 1002,
    SYSTEM_PERMISSION_DENIED = 1003,
    SYSTEM_TIMEOUT = 1004,
    SYSTEM_IO_ERROR = 1005,
    
    LOG_ERROR_BASE = 2000,
    LOG_INIT_FAILED = 2001,
    LOG_WRITE_FAILED = 2002,
    LOG_FILE_NOT_FOUND = 2003,
    LOG_INVALID_CONFIG = 2004,
    
    DATABASE_ERROR_BASE = 3000,
    DATABASE_CONNECTION_FAILED = 3001,
    DATABASE_QUERY_FAILED = 3002,
    DATABASE_TRANSACTION_FAILED = 3003,
    DATABASE_CONSTRAINT_VIOLATION = 3004,
    DATABASE_DATA_CORRUPTION = 3005,
    
    NETWORK_ERROR_BASE = 4000,
    NETWORK_CONNECTION_FAILED = 4001,
    NETWORK_TIMEOUT = 4002,
    NETWORK_PROTOCOL_ERROR = 4003,
    NETWORK_DATA_CORRUPTION = 4004,
    
    HARDWARE_ERROR_BASE = 5000,
    HARDWARE_DEVICE_NOT_FOUND = 5001,
    HARDWARE_DEVICE_BUSY = 5002,
    HARDWARE_DEVICE_ERROR = 5003,
    HARDWARE_DEVICE_OFFLINE = 5004,
    
    IMAGE_ERROR_BASE = 6000,
    IMAGE_INVALID_FORMAT = 6001,
    IMAGE_PROCESSING_FAILED = 6002,
    IMAGE_CAPTURE_FAILED = 6003,
    IMAGE_ANALYSIS_FAILED = 6004,
    
    CAMERA_CONTROL_ERROR_BASE = 6100,
    CAMERA_CONTROL_INVALID_CAMERA_TYPE = 6101,
    CAMERA_CONTROL_INVALID_CAMERA_NAME = 6102,
    CAMERA_CONTROL_CAMERA_NOT_FOUND = 6103,
    CAMERA_CONTROL_CAMERA_OPEN_FAILED = 6104,
    CAMERA_CONTROL_CAMERA_CLOSE_FAILED = 6105,
    CAMERA_CONTROL_GET_FRAME_FAILED = 6106,
    
    CAMERA_RECOGNIZE_ERROR_BASE = 6200,
    CAMERA_RECOGNIZE_TEMPLATE_SAVE_FAILED = 6201,
    CAMERA_RECOGNIZE_RECOGNITION_FAILED = 6202,
    
    HG_CUP_DET_ERROR_BASE = 6300,
    HG_CUP_DET_DETECTION_FAILED = 6301,
    HG_CUP_DET_INVALID_IMAGE = 6302,
    HG_CUP_DET_INVALID_ROI = 6303,
    HG_CUP_DET_TEMPLATE_SAVE_FAILED = 6304,
    
    UI_ERROR_BASE = 7000,
    UI_INIT_FAILED = 7001,
    UI_RESOURCE_NOT_FOUND = 7002,
    UI_LAYOUT_ERROR = 7003,
    UI_EVENT_HANDLER_ERROR = 7004,
    
    BUSINESS_ERROR_BASE = 8000,
    BUSINESS_INVALID_OPERATION = 8001,
    BUSINESS_INVALID_STATE = 8002,
    BUSINESS_DATA_VALIDATION_FAILED = 8003,
    BUSINESS_RULE_VIOLATION = 8004,
    
    THIRD_PARTY_ERROR_BASE = 9000,
    THIRD_PARTY_INIT_FAILED = 9001,
    THIRD_PARTY_API_ERROR = 9002,
    THIRD_PARTY_LICENSE_ERROR = 9003,
    THIRD_PARTY_VERSION_INCOMPATIBLE = 9004,
    
    UNKNOWN_ERROR = 9999
};

class IError {
public:
    virtual ~IError() = default;
    
    virtual HGErrorCode code() const = 0;
    virtual HGErrorSeverity severity() const = 0;
    virtual const std::string& message() const = 0;
    virtual bool hasError() const = 0;
    virtual bool isCritical() const = 0;
    
    virtual void clear() = 0;
    virtual void set(HGErrorCode code, HGErrorSeverity severity, const std::string& message) = 0;
    
    virtual std::string toString() const = 0;
};

std::string errorCodeToString(HGErrorCode code);
std::string errorSeverityToString(HGErrorSeverity severity);

}

#endif // IFERROR_H
