set(__QT_DEPLOY_TARGET_HGBaseAppModuleStatic_FILE D:/virtualMachine/github/vsproject/HGAppModule/windows_build/HGBaseAppModule/libHGBaseAppModuleStatic.a)
set(__QT_DEPLOY_TARGET_HGBaseAppModuleStatic_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_HGLogModuleStatic_FILE D:/virtualMachine/github/vsproject/HGAppModule/windows_build/HGLogModule/libHGLogModuleStatic.a)
set(__QT_DEPLOY_TARGET_HGLogModuleStatic_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_HGLogModuleRun_FILE D:/virtualMachine/github/vsproject/HGAppModule/windows_build/HGLogModule/HGLogModuleRun.exe)
set(__QT_DEPLOY_TARGET_HGLogModuleRun_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_HGLogModuleRun_RUNTIME_DLLS D:/Qt/6.9.1/mingw_64/bin/Qt6Charts.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6PrintSupport.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6Designer.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6OpenGLWidgets.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6OpenGL.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6Xml.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6Widgets.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6Gui.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6Qml.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6Network.dll;D:/Qt/6.9.1/mingw_64/bin/Qt6Core.dll)
