macro(HG_CMAKE_APPEND_UNIQUE ELEMTS ELEMT)
    list(FIND ${ELEMTS} ${ELEMT} index)
    if(index EQUAL -1)
        list(APPEND ${ELEMTS} ${ELEMT})
    endif()
endmacro()

macro(HG_CMAKE_FOLDER_APPEND SUB_DIR)
    foreach(FOLDER ${ARGN})
        if(IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${FOLDER})
            HG_CMAKE_APPEND_UNIQUE(FOLDERS ${CMAKE_CURRENT_SOURCE_DIR}/${FOLDER})
            if(IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${FOLDER}/${SUB_DIR})
                HG_CMAKE_APPEND_UNIQUE(FOLDERS ${CMAKE_CURRENT_SOURCE_DIR}/${FOLDER}/${SUB_DIR})
            endif()
        elseif(IS_DIRECTORY ${FOLDER})
            HG_CMAKE_APPEND_UNIQUE(FOLDERS ${FOLDER})
            if(IS_DIRECTORY ${FOLDER}/${SUB_DIR})
                HG_CMAKE_APPEND_UNIQUE(FOLDERS ${FOLDER}/${SUB_DIR})
            endif()
        endif()
    endforeach()
endmacro()

macro(HG_CMAKE_INCLUDE)
    set(FOLDERS "")
    HG_CMAKE_FOLDER_APPEND(inc ${ARGN})
    HG_CMAKE_FOLDER_APPEND(include ${ARGN})
    foreach(FOLDER ${FOLDERS})
        include_directories(${FOLDER})
        message(STATUS "include:${FOLDER}")
    endforeach()
endmacro()

macro(HG_CMAKE_MODULE_TARGET_INCLUDE)
    set(FOLDERS "")
    HG_CMAKE_FOLDER_APPEND(inc ${ARGN})
    HG_CMAKE_FOLDER_APPEND(include ${ARGN})
    foreach(FOLDER ${FOLDERS})
        target_include_directories(${HG_MODULE_NAME} 
        PUBLIC
        ${FOLDER})
        message(STATUS "include:${FOLDER}")
    endforeach()
endmacro()

macro(HG_CMAKE_MODULE_IF_LINK_DIRS)
    set(FOLDERS "")
    HG_CMAKE_FOLDER_APPEND(lib ${ARGN})
    foreach(FOLDER ${FOLDERS})
        target_link_directories(${HG_MODULE_NAME}_IF INTERFACE
        ${FOLDER})
        message(STATUS "linkdir:${FOLDER}")
    endforeach()
endmacro()


macro(HG_CMAKE_MODULE_DEPEND)
    message(STATUS "link:${ARGN}")
    target_link_libraries(${HG_MODULE_NAME} PRIVATE ${ARGN})
endmacro()
macro(HG_CMAKE_MODULE_DEPEND_PUB)
    message(STATUS "PUBLIC link:${ARGN}")
    target_link_libraries(${HG_MODULE_NAME} PUBLIC ${ARGN})
endmacro()

macro(HG_CMAKE_MODULE_SOURCE)
    set(FOLDERS "")
    set(MODULE_SRCS "")
    HG_CMAKE_FOLDER_APPEND(src ${ARGN})
    HG_CMAKE_FOLDER_APPEND(source ${ARGN})
    foreach(FOLDER ${FOLDERS} ${ARGN})
        set(MODULE_SRC "")
        if(IS_DIRECTORY ${FOLDER})
            aux_source_directory(${FOLDER} MODULE_SRC)
            if(MODULE_SRC)
                message(STATUS "add source:${FOLDER}")
                list(APPEND MODULE_SRCS ${MODULE_SRC})
            endif()
            # message(STATUS "MODULE_SRC:${MODULE_SRCS}")
        elseif(EXISTS ${FOLDER})
            message(STATUS "add file:${FOLDER}")
            list(APPEND MODULE_SRCS ${FOLDER})
        else()
            get_filename_component(file_extension ${FOLDER} EXT)
            # message(STATUS "${FOLDER}:" ${file_extension})
            if(NOT ${file_extension})
                message(STATUS "add file:${FOLDER}")
                list(APPEND MODULE_SRCS ${FOLDER})
            endif()
            # message(STATUS "add invaild:${FOLDER}")
            # list(APPEND MODULE_SRCS ${FOLDER})
        endif()
    endforeach()
endmacro()

macro(HG_CMAKE_ADD_INTERFACE MODULE_NAME)
    set(HG_MODULE_NAME ${MODULE_NAME})
    add_library(${MODULE_NAME}_IF INTERFACE)
    add_library(HGIF::${MODULE_NAME} ALIAS ${MODULE_NAME}_IF)
    set(FOLDERS "")
    HG_CMAKE_FOLDER_APPEND(inc ${ARGN} ${CMAKE_CURRENT_SOURCE_DIR})
    HG_CMAKE_FOLDER_APPEND(include ${ARGN} ${CMAKE_CURRENT_SOURCE_DIR})
    foreach(FOLDER ${FOLDERS})
        if(IS_DIRECTORY ${FOLDER})
            target_include_directories(${MODULE_NAME}_IF
            INTERFACE
            ${FOLDER})
            message(STATUS "[${MODULE_NAME}-IF] include:${FOLDER}")
        endif()
    endforeach()
endmacro()

macro(HG_CMAKE_ADD_MODELU MODULE_NAME)
    HG_CMAKE_ADD_INTERFACE(${MODULE_NAME} ${ARGN})
    message(STATUS "[${MODULE_NAME}-M]: ${CMAKE_CURRENT_SOURCE_DIR}")
    set(HG_MODULE_NAME ${MODULE_NAME})
    HG_CMAKE_MODULE_SOURCE(${ARGN})
    message(STATUS "[${MODULE_NAME}-M] cpp: ${MODULE_SRCS}")
    add_library(${MODULE_NAME} OBJECT ${MODULE_SRCS})
    add_library(HG::${MODULE_NAME} ALIAS ${MODULE_NAME})
    HG_CMAKE_MODULE_TARGET_INCLUDE(${ARGN} ${CMAKE_CURRENT_SOURCE_DIR})
endmacro()

macro(HG_CMAKE_ADD_SHARED MODULE_NAME)
    message(STATUS "[${MODULE_NAME}-SO]: ${CMAKE_CURRENT_SOURCE_DIR}")
    set(HG_MODULE_NAME ${MODULE_NAME})
    HG_CMAKE_MODULE_SOURCE(${ARGN})
    message(STATUS "[${MODULE_NAME}-SO] cpp: ${MODULE_SRCS}")
    add_library(${MODULE_NAME} SHARED ${MODULE_SRCS})
    add_library(HG::${MODULE_NAME} ALIAS ${MODULE_NAME})
    HG_CMAKE_MODULE_TARGET_INCLUDE(${ARGN} ${CMAKE_CURRENT_SOURCE_DIR})
    install(TARGETS ${MODULE_NAME}
    DESTINATION ${CMAKE_SOURCE_DIR}/hg_pub/${PLATFORM}/lib)
endmacro()

macro(HG_CMAKE_ADD_STATIC MODULE_NAME)
    message(STATUS "[${MODULE_NAME}-A]: ${CMAKE_CURRENT_SOURCE_DIR}")
    set(HG_MODULE_NAME ${MODULE_NAME})
    HG_CMAKE_MODULE_SOURCE(${ARGN})
    message(STATUS "[${MODULE_NAME}-A] cpp: ${MODULE_SRCS}")
    add_library(${MODULE_NAME} ${MODULE_SRCS})
    add_library(HG::${MODULE_NAME} ALIAS ${MODULE_NAME})
    HG_CMAKE_MODULE_TARGET_INCLUDE(${ARGN})
    install(TARGETS ${MODULE_NAME}
    DESTINATION ${CMAKE_SOURCE_DIR}/hg_pub/${PLATFORM}/lib)
endmacro()

macro(HG_CMAKE_ADD_EXE MODULE_NAME)
    message(STATUS "[${MODULE_NAME}-E]: ${CMAKE_CURRENT_SOURCE_DIR}")
    set(HG_MODULE_NAME ${MODULE_NAME})
    HG_CMAKE_MODULE_SOURCE(${ARGN})
    message(STATUS "[${MODULE_NAME}-E] cpp: ${MODULE_SRCS}")
    add_executable(${MODULE_NAME} ${MODULE_SRCS})
    HG_CMAKE_MODULE_TARGET_INCLUDE(${ARGN} ${CMAKE_CURRENT_SOURCE_DIR})
    message(STATUS "[${MODULE_NAME}-E] install: ${CMAKE_SOURCE_DIR}/hg_pub/app")
    install(TARGETS ${MODULE_NAME}
    RUNTIME DESTINATION ${CMAKE_SOURCE_DIR}/hg_pub/${PLATFORM}/app)
endmacro()

macro(HG_CMAKE_ADD_ELF_AND_BIN MODULE_NAME)
    message(STATUS "[${MODULE_NAME}-E]: ${CMAKE_CURRENT_SOURCE_DIR}")
    set(HG_MODULE_NAME ${MODULE_NAME}.elf)
    HG_CMAKE_MODULE_SOURCE(${ARGN})
    message(STATUS "[${MODULE_NAME}-E] cpp: ${MODULE_SRCS}")
    add_executable(${MODULE_NAME}.elf ${MODULE_SRCS})

    add_custom_command(TARGET ${MODULE_NAME}.elf POST_BUILD
        COMMAND ${CMAKE_OBJCOPY} -O binary ${MODULE_NAME}.elf ${MODULE_NAME}.bin
        COMMENT "Generating .bin file from .elf")
    HG_CMAKE_MODULE_TARGET_INCLUDE(${ARGN} ${CMAKE_CURRENT_SOURCE_DIR})
    message(STATUS "[${MODULE_NAME}-E] install: ${CMAKE_SOURCE_DIR}/hg_pub/app")
    install(TARGETS ${MODULE_NAME}.elf
        RUNTIME DESTINATION ${CMAKE_SOURCE_DIR}/hg_pub/${PLATFORM}/app)
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${MODULE_NAME}.bin
        DESTINATION ${CMAKE_SOURCE_DIR}/hg_pub/${PLATFORM}/app)
endmacro()


macro(HG_CMAKE_ADD_UNIT_TEST TEST_CASE SRC)
    message(STATUS "[${TEST_CASE}-TEST]: ${CMAKE_CURRENT_SOURCE_DIR}")
    set(HG_MODULE_NAME ${TEST_CASE})
    HG_CMAKE_MODULE_SOURCE(${SRC})
    message(STATUS "[${TEST_CASE}-TEST] cpp: ${MODULE_SRCS}")
    add_executable(${TEST_CASE} ${MODULE_SRCS})
    HG_CMAKE_MODULE_TARGET_INCLUDE(${SRC} ${CMAKE_CURRENT_SOURCE_DIR})
    message(STATUS "link:${ARGN}")
    target_link_libraries(${HG_MODULE_NAME} PRIVATE ${ARGN})
endmacro()

