set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

# 设置交叉编译工具链
set(COMPILER_PREFIX "arm-none-eabi-")
set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}g++)
set(CMAKE_AR ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}ar)
set(CMAKE_AS ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}as)
set(CMAKE_LINKER  ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}ld)
set(CMAKE_OBJCOPY ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}objcopy)
set(CMAKE_OBJDUMP ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}objdump)
set(CMAKE_SIZE    ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}size)
set(CMAKE_STRIP   ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}strip)

# 设置交叉编译参数


set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -nostdlib")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -nostdlib")
