set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(COMPILER_PREFIX "i686-w64-mingw32-")
set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}gcc-posix)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/${COMPILER_PREFIX}g++-posix)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_definitions(-D_POSIX_C_SOURCE=200809L)

set(FLAGS_COMMONS "-Wall -fPIC")
set(FLAGS_OPTIMAL "-g")
# 添加 pthread 和 std 线程支持
# set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -lwinpthread")
set(CMAKE_CXX_FLAGS "${FLAGS_COMMONS} ${FLAGS_OPTIMAL} -static -std=c++11 -fopenmp -pthread" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "${FLAGS_COMMONS} ${FLAGS_OPTIMAL}" CACHE STRING "" FORCE)
# 编译器选项
# set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_POSIX_C_SOURCE=200809L")
# set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread")
