set(FLAGS_COMMONS "-Wall -fPIC")
set(FLAGS_OPTIMAL "-g")
set(CMAKE_CXX_FLAGS "${FLAGS_COMMONS} ${FLAGS_OPTIMAL} -std=c++11 -fopenmp" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "${FLAGS_COMMONS} ${FLAGS_OPTIMAL}" CACHE STRING "" FORCE)

